UI/Controllers/workflowController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UI.Models;
using UI.Models.Record;

namespace UI.Controllers
{
    public class workflowController : BaseController
    {
        public IActionResult Dialog(int pid)
        {
            var v = new WorkflowDialogViewMode() { pid = pid,UploadGuid=BO.BAS.GetGuid(),TempGuid=BO.BAS.GetGuid() };
            
            RefreshStateDialog(v);            
            return View(v);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Dialog(Models.WorkflowDialogViewMode v, string oper,int p85id)
        {
            RefreshStateDialog(v);
            
            if (oper == "add_j02" && v.SelectedNomineeJ02ID>0)
            {
                if (v.lisTemp.Where(p=>p.p85IsDeleted==false && p.p85Prefix=="j02" && p.p85DataPID == v.SelectedNomineeJ02ID).Count() == 0)
                {
                    var c = new BO.p85Tempbox() { p85GUID = v.TempGuid, p85Prefix = "j02", p85DataPID = v.SelectedNomineeJ02ID };
                    c.p85FreeText01 = Factory.j02PersonBL.Load(v.SelectedNomineeJ02ID).FullNameDesc;
                    Factory.p85TempboxBL.Save(c);
                    RefreshStateTemp(v);
                }                                
            }
            if (oper == "add_j11" && v.SelectedNomineeJ11ID>0)
            {
                if (v.lisTemp.Where(p => p.p85IsDeleted == false && p.p85Prefix == "j11" && p.p85DataPID == v.SelectedNomineeJ11ID).Count() == 0)
                {
                    var c = new BO.p85Tempbox() { p85GUID = v.TempGuid, p85Prefix = "j11", p85DataPID = v.SelectedNomineeJ11ID };
                    c.p85FreeText01 = Factory.j11TeamBL.Load(v.SelectedNomineeJ11ID).j11Name;
                    Factory.p85TempboxBL.Save(c);
                    RefreshStateTemp(v);
                }                                    
            }
            if (oper== "delete_temp_row" && p85id > 0)
            {
                Factory.p85TempboxBL.VirtualDelete(p85id);
                RefreshStateTemp(v);               
            }
            if (!string.IsNullOrEmpty(oper))
            {
                return View(v);
            }
            if (ModelState.IsValid)
            {
                int intRet = 0;
                if (v.SelectedB06ID == 0)
                {
                    List<int> a45ids_to = null;
                    if (v.lisCommentTo != null && v.IsCommentToAll==false)
                    {
                        a45ids_to = v.lisCommentTo.Where(p=>p.a45IsManual==true).Select(p => p.a45ID).ToList();
                        if (a45ids_to.Count() == 0)
                        {
                            this.AddMessage("Chybí zaškrtnout, komu má být komentář určený.");
                            return View(v);
                        }
                    }
                    intRet = Factory.WorkflowBL.SaveWorkflowComment(v.pid, v.Comment,v.UploadGuid, a45ids_to);    //pouze zapsat komentář
                }
                else
                {                    
                    var lisNeed2Validate = Factory.WorkflowBL.GetForms4Validation(v.RecA01, v.RecB06);  //Validace uvnitř WorkflowBL v sobě nemá kontrolu vyplnění formulářů!
                    v.FormValidationErrorMessage = "";
                    foreach (var recA11 in lisNeed2Validate)
                    {
                        var cValidate = new FormValidation(Factory);
                        var ret = cValidate.GetValidateResult(recA11.pid).Take(20);
                        if (ret.Count() > 0)
                        {
                            v.FormValidationErrorMessage += "<strong style='color:green;'>" + recA11.f06Name + "</strong>";
                            foreach (var err in ret)
                            {
                                v.FormValidationErrorMessage+="<br><code>" +err.Message+"</code>: "+ err.Sekce + " / " + err.Otazka+" ("+err.OtazkaId.ToString()+")<hr>";
                            }
                            return View(v);
                        }                                                
                    }
                    var lisNominee = new List<BO.a41PersonToEvent>();
                    foreach (var cTemp in v.lisTemp.Where(p => p.p85Prefix == "j02" || p.p85Prefix == "j11"))
                    {
                        var c = new BO.a41PersonToEvent() { a01ID = v.RecA01.pid, b06ID_NomineeSource=v.RecB06.pid, a41IsAllocateAllPeriod=true };
                        if (cTemp.p85Prefix == "j02")
                        {
                            c.j02ID = cTemp.p85DataPID;
                        }
                        if (cTemp.p85Prefix == "j11")
                        {
                            c.j11ID = cTemp.p85DataPID;
                        }
                        c.a45ID = (BO.EventRoleENUM)v.RecB06.a45ID_NomineeTarget;
                        lisNominee.Add(c);
                    }
                    if (lisNominee.Count() == 0) lisNominee = null;
                    intRet = Factory.WorkflowBL.RunWorkflowStep(v.RecA01, v.RecB06, lisNominee, v.Comment, v.UploadGuid, true);
                }
                if (intRet > 0)
                {

                    v.SetJavascript_CallOnLoad(v.pid);
                    return View(v);
                }
            }
            
            this.Notify_RecNotSaved();
            return View(v);
        }

        private void RefreshStateTemp(WorkflowDialogViewMode v)
        {
            v.lisTemp = Factory.p85TempboxBL.GetList(v.TempGuid, false);
        }

        private void RefreshStateDialog(WorkflowDialogViewMode v)
        {
            v.RecA01 = Factory.a01EventBL.Load(v.pid);
            v.PermA01 = Factory.a01EventBL.InhalePermission(v.RecA01);

            
            v.lisA41 = Factory.a41PersonToEventBL.GetList(new BO.myQueryA41() { a01id = v.pid, j02id=Factory.CurrentUser.j02ID, CurrentUser = Factory.CurrentUser });
            if (Factory.App.Implementation == "HD" && Factory.CurrentUser.j04IsAllowedAllEventTypes && v.lisCommentTo==null)
            {
                v.IsCommentToAll = true;
                v.lisCommentTo = new List<BO.a45EventRole>();
                var lisx = Factory.a41PersonToEventBL.GetList(new BO.myQueryA41() { a01id = v.pid });
                var qry = from xx in lisx select new { xx.a45ID, xx.a45Name };

                foreach (var c in qry.Distinct())
                {
                    v.lisCommentTo.Add(new BO.a45EventRole() { a45ID = (int)c.a45ID, a45Name = c.a45Name});
                    
                }
            }
            RefreshStateTemp(v);
            
            var mq = new BO.myQuery("b06");
           
            mq.b02id = v.RecA01.b02ID;
            if (mq.b02id == 0) mq.b02id = -1;   //akce nemá nahozený workflow stav!!
            
            v.lisB06 = new List<BO.b06WorkflowStep>();

            if (v.RecA01.a01ParentID == 0 || (v.RecA01.a01ParentID > 0 && Factory.a01EventBL.GetList_a24(v.RecA01.pid).Where(p => p.a46ID == 5).Count() > 0))
            {
                //nabídku spustitelných kroků řešit pouze pro nadřízené akce nebo IA audit!
                var lisB06 = Factory.b06WorkflowStepBL.GetList(mq).OrderBy(p => p.b06Order).Where(p => p.b06IsManualStep == true);
                foreach (var c in lisB06)
                {
                    if (IsStepAvailable4Me(c, v))
                    {
                        if (c.b02ID_Target > 0) c.b06Name += " -> " + c.TargetStatus;
                        v.lisB06.Add(c);
                    }
                }
            }
            
            bool bolIsCommentForbidden = false;
            if (v.RecA01.b02ID > 0)
            {
                bolIsCommentForbidden = Factory.b02WorkflowStatusBL.Load(v.RecA01.b02ID).b02IsCommentForbidden;
            }
            if (bolIsCommentForbidden == false)
            {
                var c = new BO.b06WorkflowStep() { b06ID = 0, pid = 0, b06Name = Factory.tra("Doplnit pouze komentář nebo nahrát přílohu") };
                v.lisB06.Add(c);
            }
            if (v.SelectedB06ID > 0)
            {
                v.RecB06 = Factory.b06WorkflowStepBL.Load(v.SelectedB06ID);
            }
            else
            {
                v.RecB06 = new BO.b06WorkflowStep() { b06ID = v.SelectedB06ID, pid = v.SelectedB06ID };
            }
            

        }

        private bool IsStepAvailable4Me(BO.b06WorkflowStep rec, WorkflowDialogViewMode v)
        {
            var lisB08 = Factory.b06WorkflowStepBL.GetListB08(rec.pid);
            var mq = new BO.myQuery("a39");
            mq.a03id = v.RecA01.a03ID;
            var lisA39 = Factory.a39InstitutionPersonBL.GetList(mq).Where(p => p.j02ID == Factory.CurrentUser.j02ID);
          
            foreach (var c in lisB08)
            {
                switch (c.a45ID)
                {
                    case 1: //člen týmu
                        if (v.PermA01.HasPerm(BO.a01EventPermissionENUM.ShareTeam_Member))
                        {
                            return true;
                        }
                        break;
                    case 2: //vedoucí týmu
                        if (v.PermA01.HasPerm( BO.a01EventPermissionENUM.ShareTeam_Leader))
                        {
                            return true;
                        }
                        break;
                    case 6: //přizvaná osoba
                        if (v.PermA01.HasPerm(BO.a01EventPermissionENUM.ShareTeam_InvitedPerson))
                        {
                            return true;
                        }
                        break;
                    case 3: //zadavatel
                        if (v.PermA01.HasPerm(BO.a01EventPermissionENUM.HD_Requestor))
                        {
                            return true;

UI/Views/workflow/Dialog.cshtml
@model UI.Models.WorkflowDialogViewMode
@inject BL.RunningApp _app
@inject BL.Factory _f

@{
    Model.PageTitle = _f.tra("Posunout | Doplnit");
    Layout = "~/Views/Shared/_LayoutModal.cshtml";
    
    if (Model.RecA01 == null)
    {
        return;
    }


}

@addTagHelper *, UI

<h4>
    @Model.PageTitle: @(Model.RecA01.a01Signature)
    @if (Model.RecA01.b02ID > 0)
    {
        <span>, @_f.tra("aktuální stav"):</span>
        <strong style="margin-left:10px;">@Model.RecA01.b02Name</strong>
    }
</h4>

<div class="bg-light" style="padding:10px;">
    <button id="cmdSave" type="button" class="btn btn-success">@_f.tra("Uložit změny")</button>
    <button type="button" id="cmdClose" onclick="_window_close()" class="btn btn-light" lang="uk">@_f.tra("Zavřít")</button>
    <button type="button" onclick="_helppage()" class="btn btn-light"><b>? </b>@_f.tra("Nápověda")</button>

</div>

<form id="form1" asp-controller="workflow" asp-action="Dialog" method="POST">

    <input type="hidden" asp-for="@Model.pid" />
    <input type="hidden" asp-for="@Model.UploadGuid" />
    <input type="hidden" asp-for="@Model.TempGuid" />

    <div class="modal_record_container">
        <myradiolist asp-for="@Model.SelectedB06ID" datasource="@Model.lisB06" valuefield="pid" textfield="b06Name" event_after_changevalue="b06id_onchange"></myradiolist>


        @if (Model.RecB06.b06IsNominee)
        {
            <div class="card">
                <div class="card-header">
                    Nominace řešitele
                    <button type="button" class="btn btn-primary" onclick="myself_nominee_add()">Vybrat sebe</button>
                </div>
                <div class="card-body">
                    <mycombo entity="j02Person" asp-for="@Model.SelectedNomineeJ02ID" selectedtext="@Model.SelectedNomineePerson" filter-flag="1" event_after_changevalue="j02id_nominee_add" placeholder="Vybrat osobu..."></mycombo>
                    <mycombo entity="j11Team" asp-for="@Model.SelectedNomineeJ11ID" selectedtext="@Model.SelectedNomineeTeam" event_after_changevalue="j11id_nominee_add" placeholder="Vybrat tým..."></mycombo>
                    <table>
                        @foreach (var c in Model.lisTemp)
                        {
                            <tr>
                                <td style="font-weight:bold;">
                                    @c.p85FreeText01
                                </td>
                                <td>
                                    <button type="button" class="btn btn-danger" title="Odstranit" onclick="delete_temp_row(@(c.p85ID))">x</button>
                                </td>
                            </tr>
                        }
                    </table>
                </div>
            </div>
        }
        @if(string.IsNullOrEmpty(Model.FormValidationErrorMessage)==false)
        {
            <div class="card">
                <div class="card-header text-danger">@_f.tra("Zjištěné nedostatky ve vyplňovaných formulářích")</div>
                <div class="card-body">
                    @Html.Raw(Model.FormValidationErrorMessage)
                </div>
            </div>
        }

        @if(Model.SelectedB06ID==0 && Model.lisCommentTo != null)
        {
            <div class="card">
                <div class="card-header">
                    @_f.tra("Komu je komentář určený?")
                </div>
                <div class="card-body">
                    <div>
                        <input type="checkbox" asp-for="@Model.IsCommentToAll" />
                        <label for="IsCommentToAll">@_f.tra("Všichni účastníci akce (požadavku)")</label>
                        <hr />
                    </div>
                    <div id="divCommentTo">
                        @for (int i = 0; i < Model.lisCommentTo.Count(); i++)
                        {
                            <input type="checkbox" asp-for="@Model.lisCommentTo[i].a45IsManual" />
                            <label for="lisCommentTo_@(i)__a45IsManual">@(Model.lisCommentTo[i].a45Name)</label>
                            <input type="hidden" asp-for="@Model.lisCommentTo[i].a45Name" />
                            <input type="hidden" asp-for="@Model.lisCommentTo[i].a45ID" />
                        }
                    </div>
                </div>
            </div>
            
        }
        <div class="my-2">
            <textarea asp-for="@Model.Comment" class="form-control" placeholder="@_f.tra("Doplnit komentář")..."></textarea>
            
        </div>

        <iframe id="fraUpload" src="/FileUpload/Index?prefix=a01&guid=@Model.UploadGuid" height="220" scrolling="yes"></iframe>
    </div>
</form>

<script type="text/javascript">
    $(document).ready(function () {

        $("#cmdSave").click(function () {
            $(this).text("Processing...");
            $(this).attr("disabled", true);
            form1.submit();

        });

        $("#IsCommentToAll").on("change", function () {
            form1.action = "/workflow/Dialog?oper=postback";
            form1.submit();
        });

       @if (Model.IsCommentToAll)
       {            
        @:$("#divCommentTo").css("display", "none");        
       }


        var offset = $("#fraUpload").offset();
        var h_vertical = _device.innerHeight - offset.top;
        h_vertical = parseInt(h_vertical) - 20;
        if (_device.type === "Phone") {
            h_vertical = 400;
        }
        $("#fraUpload").css("height", h_vertical + "px");
    })

    function b06id_onchange(b06id) {
        form1.action = "/workflow/Dialog?oper=postback";
        form1.submit();
    }



    function j02id_nominee_add(j02id) {
        form1.action = "/workflow/Dialog?oper=add_j02";
        form1.submit();
    }
    function myself_nominee_add() {
        $("#SelectedNomineeJ02ID").val(@_f.CurrentUser.j02ID);
        form1.action = "/workflow/Dialog?oper=add_j02";
        form1.submit();
    }
    function j11id_nominee_add(j11id) {
        form1.action = "/workflow/Dialog?oper=add_j11";
        form1.submit();
    }
    function delete_temp_row(p85id) {
        form1.action = "/workflow/Dialog?oper=delete_temp_row&p85id=" + p85id;
        form1.submit();
    }

    function run() {
        form1.submit();
    }


</script>