UI/Models/a01/a01CreateA57ViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UI.Models
{
    public class a01CreateA57ViewModel:BaseViewModel
    {
        public BO.a01Event Rec { get; set; }
        public int a57ID { get; set; }
        public BO.a57AutoEvaluation RecA57 { get; set; }
        public int a10ID { get; set; }        
        public BO.a10EventType RecA10 { get; set; }
        public int a08ID { get; set; }
        public BO.a08Theme RecA08 { get; set; }
        public IEnumerable<BO.a12ThemeForm> lisA12 { get; set; }
        public List<int> lisSelectedF06IDs { get; set; }
        public int a03ID { get; set; }
        public BO.a03Institution RecA03 { get; set; }
        
        public IEnumerable<BO.o27Attachment> lisO27 { get; set; }
    }
}

UI/Controllers/a01CreateA57Controller.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UI.Models;

namespace UI.Controllers
{
    public class a01CreateA57Controller : BaseController
    {
        public IActionResult Index(int a57id,int a03id)
        {
            var v = new a01CreateA57ViewModel() { a57ID=a57id,a03ID=a03id };
            if (v.a57ID == 0)
            {
                return this.StopPage(true,"Na vstupu chybí vazba na autoevaluační šablonu.");
            }
            if (v.a03ID == 0)
            {
                return this.StopPage(true, "Na vstupu chybí vazba na školu.");
            }
            RefreshState(v);
            
            
            
            return View(v);
        }


        private void RefreshState(a01CreateA57ViewModel v)
        {
            if (v.lisSelectedF06IDs == null)
            {
                v.lisSelectedF06IDs = new List<int>();
            }
            if (v.RecA57 == null)
            {
                v.RecA57 = Factory.a57AutoEvaluationBL.Load(v.a57ID);
                v.a10ID = v.RecA57.a10ID;
                v.a08ID = v.RecA57.a08ID;
            }
            v.RecA03 = Factory.a03InstitutionBL.Load(v.a03ID);

            v.RecA10 = Factory.a10EventTypeBL.Load(v.a10ID);
            v.RecA08 = Factory.a08ThemeBL.Load(v.a08ID);
            v.lisA12 = Factory.a08ThemeBL.GetListA12(v.RecA08.pid);

            v.lisO27 = Factory.o27AttachmentBL.GetList(new BO.myQueryO27() { a57id = v.a57ID },null);

            if (v.Rec == null)
            {
                v.Rec = new BO.a01Event();
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(Models.a01CreateA57ViewModel v, string oper)
        {
            RefreshState(v);
            
            if (oper != null)
            {               
                return View(v);
            }
            

            if (ModelState.IsValid)
            {
                //if (v.lisSelectedF06IDs.Where(p => p > 0).Count() == 0)
                //{
                //    this.AddMessage("Musíte zaškrtnout minimálně jeden formulář.");return View(v);
                //}
                BO.a01Event c = new BO.a01Event();
                c.a57ID = v.RecA57.pid;
                c.a10ID = v.RecA57.a10ID;
                c.a08ID = v.RecA57.a08ID;
                c.a03ID = v.a03ID;              
                c.j02ID_Issuer = Factory.CurrentUser.j02ID;
                
                if (!(DateTime.Today >= v.RecA57.a57CreateFrom && DateTime.Today <= v.RecA57.a57CreateUntil))
                {
                    this.AddMessage("Časová závora autoevaluační šablony nedovoluje založit akci.");return View(v);
                }
                var recA10 = Factory.a10EventTypeBL.Load(v.RecA57.a10ID);
                if (recA10.a10IsUse_Period)
                {
                    c.a01DateFrom = DateTime.Today;
                    c.a01DateUntil = Convert.ToDateTime(c.a01DateFrom).AddDays(90);
                    if (c.a01DateUntil>v.RecA57.a57CreateUntil) c.a01DateUntil=v.RecA57.a57CreateUntil;
                }

                var lisA11 = new List<BO.a11EventForm>();
                foreach(var f06id in v.lisSelectedF06IDs.Where(p => p > 0))
                {
                    lisA11.Add(new BO.a11EventForm() { f06ID = f06id });
                }

                c.pid = Factory.a01EventBL.Create(c, true, lisA11, null, null, null);
                if (c.pid > 0)
                {

                    return RedirectToAction("RecPageA57", "a01", new { pid = c.pid });

                }
            }

            this.Notify_RecNotSaved();
            return View(v);
        }

    }


}

UI/Views/a01CreateA57/Index.cshtml
@model a01CreateA57ViewModel
@inject BL.Factory _f

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    if (Model.Rec == null) return;
    Model.PageTitle = _f.tra("Autoevaluace");
}


@addTagHelper *, UI


<h4 class="px-2">@Model.RecA57.a57Name</h4>

<div class="bg-light" style="padding:10px;">
    <button id="cmdSave" class="btn btn-success">@_f.tra("Uložit změny")</button>
    <a id="cmdCancel" href="/Dashboard/School" class="btn btn-light">@_f.tra("Zrušit")</a>


</div>

<div class="modal_record_container">
    <form id="form1" asp-controller="a01CreateA57" asp-action="Index" method="POST">
        <input type="hidden" asp-for="@Model.a57ID" />
        <input type="hidden" asp-for="@Model.a03ID" />

        <div class="row my-2">
            <label class="col-sm-1 col-md-2 col-form-label">@_f.tra("Škola"):</label>
            <div class="col-sm-11 col-md-10">
                <myval value="@Model.RecA03.a03Name" hoverprefix="a03" hoverpid="@Model.RecA03.pid"></myval>
            </div>
        </div>
        <div class="row my-2">
            <label class="col-sm-1 col-md-2 col-form-label">@_f.tra("Typ akce"):</label>
            <div class="col-sm-11 col-md-10">
                <myval value="@Model.RecA10.a10Name" hoverprefix="a10" hoverpid="@Model.RecA10.pid"></myval>
            </div>
        </div>
        <div class="row my-2">
            <label class="col-sm-1 col-md-2 col-form-label">@_f.tra("Téma akce"):</label>
            <div class="col-sm-11 col-md-10">
                <myval value="@Model.RecA08.a08Name" hoverprefix="a08" hoverpid="@Model.RecA08.pid"></myval>
            </div>
        </div>
        <div class="row my-2">
            <label class="col-sm-1 col-md-2 col-form-label">@_f.tra("Časová závora akcí"):</label>
            <div class="col-sm-11 col-md-10">
                <myval value="@(BO.BAS.ObjectDate2String(Model.RecA57.a57CreateFrom)+" - "+BO.BAS.ObjectDate2String(Model.RecA57.a57CreateUntil))"></myval>
            </div>
        </div>

        <div class="card">
            <div class="card-header">
                @_f.tra("Formuláře")
            </div>
            <div class="card-body">
                <mycheckboxlist asp-for="@Model.lisSelectedF06IDs" datasource="@Model.lisA12" valuefield="f06ID" textfield="f06Name" cssclassfield="CssClass"></mycheckboxlist>
            </div>
        </div>
    </form>

    <table>
        @foreach (var c in Model.lisO27)
        {
            <tr>
                
                <td>
                    @c.o13Name
                </td>

                <td>
                    <a target="_blank" href="/FileUpload/FileDownloadInline?downloadguid=@c.o27DownloadGUID">@c.o27OriginalFileName</a>
                </td>
                <td>
                    @(BO.BAS.FormatFileSize(c.o27FileSize))
                </td>
               
            </tr>
        }
    </table>
</div>

    



    <script type="text/javascript">

        $(document).ready(function () {

            $("#cmdSave").click(function () {
                $(this).text("Processing...");
                $(this).attr("disabled", true);
                form1.submit();


            });



        });




        function refresh() {
            form1.action = "/a01CreateA57/Index?oper=postback";
            form1.submit();
        }


    </script>